---
language: php
php:
- 5.4
sudo: false
before_script:
- "curl -LSs http://box-project.org/installer.php | php"
- "composer install --prefer-source --dev --no-interaction"
script:
- "php ./box.phar build"
- "php ./sapi-client.phar"
after_success:
  - "CURRENT_TAG=`git describe --tags HEAD`"
  - "echo $CURRENT_TAG"
  - "mkdir builds"
  - "cp ./sapi-client.phar ./builds/sapi-client.$CURRENT_TAG.phar"
  - "cp ./sapi-client.phar ./builds/sapi-client.phar"
addons:
  artifacts: true
  s3_region: "us-east-1"
  paths:
    - "builds"
env:
 global:
   - "ARTIFACTS_BUCKET=keboola-storage-api-cli"
   - secure: "Heq2XGSw+BPQS8Q7NUsGuf4HQ/4IMoUfxE+Rt+oCi9IRc/27RFgNcBUkueuA\nDET7MGVkMMzyDKcvxEucYWDCC3jyCxAS1zgJq/kdosBc4wxMgt5v0aBYQokR\nUOK9zBe5X2fhnSbaIrVXDOj16pO6nGpKoIFozTPdVPTltbnBNU8="
   - secure: "AU9XR8b1g7YZGbWvl6UuaaTCaW8NQq9ycVV1fH/lrlq367Vj19tiYH6F+txH\nFkeyGduwoQtH6pP/uHF03F5dBy/9kFAywFxzNbh+Q+OK7s/oo5Lem9yWGTmv\ni2F9T0loE0kOoLellRNd7lijkK9MpP65u0fQDdi+hf1wHGuFDDw="
