sudo: required
language: bash
services:
  - docker
install:
  - docker-compose build --build-arg KEBOOLA_STORAGE_API_CLI_VERSION=$TRAVIS_TAG app
  - docker-compose run --rm app php tests/loadToS3.php
script:
  - docker-compose run --rm app composer ci
  - docker run --rm keboola/storage-api-cli
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
