sudo: required
language: bash
services:
  - docker
install:
  - docker-compose build
  - docker-compose run --rm tests-ci php tests/loadToS3.php
script:
  - docker-compose run --rm tests-ci
  - docker run --rm keboola/storage-api-cli
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
