language: php
matrix:
  include:
    - php: 5.6
      before_script:
        - curl -LSs http://box-project.github.io/box2/installer.php | php
        - composer install --prefer-source --dev --no-interaction

      script:
        - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
        #- php vendor/bin/phpunit --testsuite storage-api-cli
        #- php ./box.phar build
        #- php ./sapi-client.phar
        
      after_success:
        - CURRENT_TAG=`git describe --tags HEAD`
        - echo $CURRENT_TAG
        - mkdir builds
        - cp ./sapi-client.phar ./builds/sapi-client.$CURRENT_TAG.phar
        - cp ./sapi-client.phar ./builds/sapi-client.phar    
#    php: 7.0
#    php: 7.1
    - php: development
      services:
        - docker
      before_script:
        - docker-compose build      
      script:
        - docker-compose run --rm tests
      after_success:
        - docker images



deploy:
  - provider: s3
    bucket: keboola-storage-api-cli
    local-dir: builds
    upload-dir: builds
    acl: public_read
    skip_cleanup: true
    detect_encoding: true
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_KEY"
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      tags: true