version: '2'
services:
  app:
    build: .
    image: keboola/storage-api-cli
    command: ./phpunit.sh
    entrypoint: []
    environment:
      - TEST_BACKUP_AWS_ACCESS_KEY_ID
      - TEST_BACKUP_AWS_SECRET_ACCESS_KEY
      - TEST_BACKUP_S3_BUCKET
      - TEST_RESTORE_AWS_ACCESS_KEY_ID
      - TEST_RESTORE_AWS_SECRET_ACCESS_KEY
      - TEST_RESTORE_S3_BUCKET
      - TEST_STORAGE_API_SECONDARY_TOKEN
      - TEST_STORAGE_API_TOKEN
      - TEST_STORAGE_API_URL
      - TEST_AWS_REGION
  dev:
    image: keboola/storage-api-cli
    entrypoint: []
    command: ./phpunit.sh
    volumes:
      - .:/code
    environment:
      - TEST_BACKUP_AWS_ACCESS_KEY_ID
      - TEST_BACKUP_AWS_SECRET_ACCESS_KEY
      - TEST_BACKUP_S3_BUCKET
      - TEST_RESTORE_AWS_ACCESS_KEY_ID
      - TEST_RESTORE_AWS_SECRET_ACCESS_KEY
      - TEST_RESTORE_S3_BUCKET
      - TEST_STORAGE_API_SECONDARY_TOKEN
      - TEST_STORAGE_API_TOKEN
      - TEST_STORAGE_API_URL
      - TEST_AWS_REGION
